baseline_parameters:
  n_groups: 1    # general, subpop1, subpop2
  desired_r0: 12.0
  k_i: [10]
  k_g1: 0.0
  k_g2: 0.0
  k_21: 0.0
  n_e_compartments: 2    # number of chained E compartments
  latent_duration: 10.5
  n_i_compartments: 2    # number of chained I compartments
  infectious_duration: 9.0
  pop_sizes: [5000]    # population sizes
  I0: [5]     # initially infected
  vaccine_uptake_start_day:  30
  vaccine_uptake_duration_days: 30 # duration of vaccine uptake campaign
  vaccinated_group: 0
  vaccine_efficacy_2_dose: 0.97
  vaccine_efficacy_1_dose: 0.93
  isolation_success: 0.8
  symptomatic_isolation_start_day: 0
  symptomatic_isolation_duration_days: 365
  pre_rash_isolation_start_day: 400
  pre_rash_isolation_duration_days: 100
  pre_rash_isolation_success: 0.0
  tf: 365        # total time modeled
  n_replicates: 1000
  seed: 123

grid_parameters:
  initial_coverage_scenario: ['low', 'medium', 'optimistic'] #
  total_vaccine_uptake_doses: [0, 250] # constant, to be divided out among the days

nested_parameters:
  - initial_coverage_scenario: 'low'
    initial_vaccine_coverage: [0.80]
  - initial_coverage_scenario: 'medium'
    initial_vaccine_coverage: [0.90]
  - initial_coverage_scenario: 'optimistic'
    initial_vaccine_coverage: [ 0.95]
