baseline_parameters:
  n_groups: 1    # general, subpop1, subpop2
  desired_r0: 12.0
  k_i: [10.]
  k_g1: 0.1
  k_g2: 0.01
  k_21: 0.01
  n_e_compartments: 2    # number of chained E compartments
  latent_duration: 10.5
  n_i_compartments: 2    # number of chained I compartments
  infectious_duration: 9.0
  pop_sizes: [15000]    # population sizes
  I0: [5]     # initially infected
  vaccine_uptake_start_day: 0
  vaccine_uptake_duration_days: 21
  use_prop_vaccine_uptake: true      # if true for the app,
  total_vaccine_uptake_doses: 20.0   # then prop unvax that get vax, else absolute number of doses
  vaccinated_group: 0
  isolation_success: 0.75 # informed by 2017 Minnesota study
  symptomatic_isolation_start_day: 0
  symptomatic_isolation_duration_days: 365
  pre_rash_isolation_success: 0.10 # not informed by data
  pre_rash_isolation_start_day: 0
  pre_rash_isolation_duration_days: 365
  IHR: 0.2 # Infection Hospitalization Rate
  tf: 365        # total time modeled
  n_replicates: 100
  seed: 123
  initial_vaccine_coverage: [0.80]
