# This file is automatically generated by the Makefile.
# Do not edit this file directly.
# This file contains the version information for the metapop package.
__all__ = ["__version__", "__versiondate__", "__git_commit__"]

__version__ = "v1.0.0"
__versiondate__ = "2025-07-25"
__git_commit__ = "a8c84d87647747eac55975fb213b8a3f2e3b2217"  # pragma: allowlist secret
