# This file is automatically generated by the Makefile.
# Do not edit this file directly.
# This file contains the version information for the metapop package.
__all__ = ["__version__", "__versiondate__", "__git_commit__"]

__version__ = "1.0.1"
__versiondate__ = "2025-08-07"
__git_commit__ = "41d4381bd23b915f45fe13de485abcb90058e7b8"  # pragma: allowlist secret
