# This file is automatically generated by the Makefile.
# Do not edit this file directly.
# This file contains the version information for the metapop package.
__all__ = ["__version__", "__versiondate__", "__git_commit__"]

__version__ = "1.0.3"
__versiondate__ = "2026-07-13"
__git_commit__ = "fd23da4329f34db916f4c2dbe1394a73456fdd39"  # pragma: allowlist secret
