baseline_parameters:
  n_groups: 3    # general, subpop1, subpop2
  desired_r0: 12.0
  k_i: [10, 10, 10]
  k_g1: 0.1
  k_g2: 0.01
  k_21: 0.01
  n_e_compartments: 2    # number of chained E compartments
  latent_duration: 10.5
  n_i_compartments: 2    # number of chained I compartments
  infectious_duration: 9.0
  pop_sizes: [40000, 5000, 5000]    # population sizes
  I0: [0, 5, 0]     # initially infected
  initial_vaccine_coverage: [0.95, 0.8, 0.8]
  vaccine_uptake_start_day:  30
  vaccine_uptake_duration_days: 30 # duration of vaccine uptake campaign
  symptomatic_isolation_duration_days: 365
  pre_rash_isolation_duration_days: 365
  vaccinated_group: 2
  isolation_success: 0.80
  pre_rash_isolation_success: 0.80
  tf: 365        # total time modeled
  n_replicates: 1000
  seed: 123

grid_parameters:
  symptomatic_isolation_start_day: [0, 400]
  pre_rash_isolation_start_day: [0, 400]
  total_vaccine_uptake_doses: [0, 500] # constant, to be divided out among the days
