baseline_parameters:
  n_groups: 3    # general, subpop1, subpop2
  beta_within: 1.0  # within group
  beta_general: 0.001 # general to sub
  desired_r0: 12.0
  n_e_compartments: 2    # number of chained E compartments
  sigma: 0.19    # 2 * 1/latent_duration
  n_i_compartments: 2    # number of chained I compartments
  gamma: 0.25   # 2 * 1/infectious_duration
  iota: 0.0      # spontaneous infection rate
  pop_sizes: [40000, 5000, 5000]    # population sizes
  I0: [0, 5, 0]     # initially infected
  vaccine_uptake: FALSE
  vaccine_uptake_days: [0]
  vaccine_updake_doses: [0]
  tf: 365        # total time modeled
  n_replicates: 1000
  seed: 123

grid_parameters:
  initial_coverage_scenario: ['low', 'medium', 'optimistic']
  connectivity_scenario: [1.0, 10.0, 50.0] #
  beta_small: [0.001, 0.01]   # sub1 to sub2

nested_parameters:
  - initial_coverage_scenario: 'low'
    initial_vaccine_coverage: [0.95, 0.75, 0.75]
  - initial_coverage_scenario: 'medium'
    initial_vaccine_coverage: [0.95, 0.8, 0.8]
  - initial_coverage_scenario: 'optimistic'
    initial_vaccine_coverage: [0.95, 0.9, 0.9]
