baseline_parameters:
  n_groups: 2    # general and sub-population (usually a lower vaccination rate)
  beta: [[0.05, 0.05], [0.05, 0.3]] # beta matrix describes contact rates within and between groups
  initial_vaccine_coverage: [0.50, 0.98]
  vaccine_uptake: FALSE
  vaccine_uptake_days: [0]
  vaccine_updake_doses: [0]
  sigma1: 0.25    # 1/latent_duration*2
  sigma2: 0.25    # 1/latent_duration*2
  gamma1: 0.4   # 1/infectious_duration*2
  gamma2: 0.4   # 1/infectious_duration*2
  iota: 0.0      # spontaneous infection rate
  N: [4400, 17600]    # population sizes
  I0: [1, 1]     # initially infected
  dt: 1.0        # model units (one day)
  tf: 200        # total time modeled
  tl: 200        # times the model is evaluated
  n_replicates: 100
  seed: 123
  beta_2_low: 0.1 #for demonstrating how to calibrate the 4h beta value, here are ranges for samples replace with beta_lower
  beta_2_high: 0.5
