baseline_parameters:
  n_groups: 2    # residents + HCW
  beta: [[0.05, 0.05], [0.05, 0.3]]
  sigma: 0.25    # 1/latent_duration
  gamma: 0.143   # 1/infectious_duration
  iota: 0.0      # spontaneous infection rate
  N: [78, 22]    # population sizes
  I0: [1, 1]     # initially infected
  dt: 1.0        # model units (one day)
  tf: 200        # total time modeled
  tl: 200        # times the model is evaluated
  n_replicates: 10
  seed: 1
