baseline_parameters:
  n_groups: 2    # mennonite + non
  beta: [[0.05, 0.05], [0.05, 0.3]] # split beta into contact + susceptibility
  beta_upper: [[0.05, 0.05], [0.05, 0.3]]
  beta_lower: [[0.05, 0.05], [0.05, 0.3]]
  sigma: 0.125    # 1/latent_duration
  gamma: 0.2   # 1/infectious_duration
  iota: 0.0      # spontaneous infection rate
  N: [4400, 17600]    # population sizes
  I0: [1, 1]     # initially infected
  dt: 1.0        # model units (one day)
  tf: 200        # total time modeled
  tl: 200        # times the model is evaluated
  n_replicates: 100
  seed: 123
  beta_2_low: 0.1 #for demonstrating how to calibrate the 4h beta value, here are ranges for samples replace with beta_lower
  beta_2_high: 0.5
