baseline_parameters:
  n_groups: 1    # general, subpop1, subpop2
  desired_r0: 12.0
  k_i: [10.]
  k_g1: 0.1
  k_g2: 0.01
  k_21: 0.01
  n_e_compartments: 2    # number of chained E compartments
  latent_duration: 10.5
  n_i_compartments: 2    # number of chained I compartments
  infectious_duration: 9.0
  pop_sizes: [15000]    # population sizes
  I0: [5]     # initially infected
  vaccine_efficacy_2_dose: 0.97
  vaccine_efficacy_1_dose: 0.93
  vaccine_uptake_duration_days: 21 # duration of vaccine uptake campaign
  symptomatic_isolation_duration_days: 365
  isolation_success: 0.50 # isolation_adherance(0.5)*isolation_reduction (1.0)
  pre_rash_isolation_success: 0.3 #quarantine_adherance(0.5)*reduction(0.6)
  pre_rash_isolation_duration_days: 365
  vaccinated_group: 0
  IHR: 0.15 #infection hospitalization rate
  tf: 365        # total time modeled
  n_replicates: 1000
  symptomatic_isolation_start_day: 4
  pre_rash_isolation_start_day: 4
  total_vaccine_uptake_doses: 500
  vaccine_uptake_start_day: 4
  seed: 123

grid_parameters:
  initial_vaccine_coverage: [[0.80], [0.85], [0.90], [0.95]]
  intervention_delay: [4, 18, 32, 46, 60, 74, 88, 102, 116]
