name: Mirror to cdcgov github org

on:
  push:
    branches:
      - production

jobs:
  sync-cdcent-cdcgov:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: production
          fetch-depth: 0

      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: "${{ vars.GIT_MIRROR_APP_ID }}"
          private-key: "${{ secrets.GIT_MIRROR_APP_PRIVATE_KEY }}"
          owner: cdcgov
          repositories: |
            metapop-model

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name 'github-automation'
          git config --global user.email 'noreply@github.com'
          # Force-pushing to ensure the CDCgov repository mirrors the production branch exactly.
          git push git@github.com:CDCgov/metapop-model.git production:main -f
